version: '3.9'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3333:3306


  php-apache:
    # image: php-apache
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
  
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./src:/var/www/html/src
    ports:
      - 80:80