name: Build and Push Docker images
run-name: ${{ github.actor }} is triggering Build and Push Docker images 🚀
on:
  push:
    branches:
      - release
concurrency: build_and_push_docker
jobs:
  build-anh-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3

      # Check if backend or frontend src folder has changes
      - name: Check if backend or frontend src folder has changes
        uses: dorny/paths-filter@v2
        id: detect-changes
        with:
          filters: |
            src:
              - 'src/**'
            index:
              - 'index.php'

      - id: image-tag
        run: |
          current=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_REPO }}/tags" |  
          jq '."results"[]["name"]' | sed -n 1p | cut -d'"' -f2)
          newBackendTag=`expr $current + 1`
          echo "::set-output name=newImageTag::$(echo $newImageTag)"

      # Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # If have changes --> deploy
      - name: Run build and push image if changes exist
        if: steps.detect-changes.outputs.src == 'true' || steps.detect-changes.outputs.index == 'true'
        run: |
          bash -x build_and_push.sh ${{ steps.image-tag.outputs.newImageTag }}
          exit 0