name: Create pull request to release
run-name: ${{ github.actor }} is triggering Create PR to release🚀
on:
  push:
    branches:
      - "minh-dev"
concurrency: create-pull-request-to-release
jobs:
  create-pull-request-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "release" and .headRefName == "${{ github.ref_name }}"))
                  | length
              ')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      # - name: Create Pull Request to release
      #   if: "!steps.check.outputs.skip"
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const { repo, owner } = context.repo;
      #       const result = await github.rest.pulls.create({
      #         title: '${{ github.ref_name }} Sync : Auto Generated PR to release',
      #         owner,
      #         repo,
      #         head: '${{ github.ref_name }}',
      #         base: 'release',
      #         body: [
      #           'This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script).',
      #           '@anhminhbo, Please help review this pull request.',
      #           'Please refer to commit messages below to know what changes has been made.'
      #         ].join('\n')
      #       });
      #       github.rest.issues.addLabels({
      #         owner,
      #         repo,
      #         issue_number: result.data.number,
      #         labels: ['feature', 'automated PR to release']
      #       });

      - name: Create Pull Request to release
        if: "!steps.check.outputs.skip"
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          branch: release
          base: minh-dev
          commit-message: Create pr to release
          title: 'Auto PR to release'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: report, automated pr



